import { useMemo } from 'react';
import {
    MaterialReactTable,
    useMaterialReactTable,
} from 'material-react-table';
import TaskAltIcon from '@mui/icons-material/TaskAlt';
import CancelOutlinedIcon from '@mui/icons-material/CancelOutlined';
import { red } from '@mui/material/colors';

//nested data is ok, see accessorKeys in ColumnDef below
const data = [
    {
     "DATE_ADDED": "12\/28\/2023 06:07",
     "ORDER_NUMBER": 1110711,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DM jrnl",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI DE (Germany)",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "12\/29\/2023 03:19",
     "ORDER_NUMBER": 1110717,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DNP Book w\/o flg v12-29.1",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 05:15",
     "ORDER_NUMBER": 1110718,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DNP Book wtoutflg",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI DE (Germany)",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 05:42",
     "ORDER_NUMBER": 1110719,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "jrnl 29 Dec",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 06:06",
     "ORDER_NUMBER": 1110720,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "jrnl 29 Dec 1",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 06:20",
     "ORDER_NUMBER": 1110721,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "jrnl 29 Ver 1",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 06:38",
     "ORDER_NUMBER": 1110722,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 06:48",
     "ORDER_NUMBER": 1110723,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "12\/29\/2023 07:13",
     "ORDER_NUMBER": 1110724,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/02\/2024 08:13",
     "ORDER_NUMBER": 1111277,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI DE (Germany)",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/02\/2024 08:19",
     "ORDER_NUMBER": 1111278,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/02\/2024 08:43",
     "ORDER_NUMBER": 1111279,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/03\/2024 04:05",
     "ORDER_NUMBER": 1111368,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/03\/2024 04:29",
     "ORDER_NUMBER": 1111371,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/03\/2024 04:39",
     "ORDER_NUMBER": 1111372,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "jrnl 29 Dec 1",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/04\/2024 02:12",
     "ORDER_NUMBER": 1111407,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/04\/2024 02:41",
     "ORDER_NUMBER": 1111409,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK book",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/04\/2024 04:57",
     "ORDER_NUMBER": 1111472,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK Fresh",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
    },
    {
     "DATE_ADDED": "01\/04\/2024 05:28",
     "ORDER_NUMBER": 1111474,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "VK DNP Jrnl",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 05:28",
     "ORDER_NUMBER": 1111475,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "Devs book",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 05:34",
     "ORDER_NUMBER": 1111476,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 05:52",
     "ORDER_NUMBER": 1111478,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "NDJ2024",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 05:59",
     "ORDER_NUMBER": 1111480,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "Devs book",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 06:06",
     "ORDER_NUMBER": 1111481,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "test jrnl 22",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 06:16",
     "ORDER_NUMBER": 1111482,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "04-Jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 06:29",
     "ORDER_NUMBER": 1111483,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 07:29",
     "ORDER_NUMBER": 1111484,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 07:32",
     "ORDER_NUMBER": 1111485,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 07:40",
     "ORDER_NUMBER": 1111486,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK book qtychk",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 07:41",
     "ORDER_NUMBER": 1111487,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:09",
     "ORDER_NUMBER": 1111488,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK 4 Jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:15",
     "ORDER_NUMBER": 1111489,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK 4 Jan1",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:16",
     "ORDER_NUMBER": 1111490,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK book SSD-5329 tst",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:16",
     "ORDER_NUMBER": 1111491,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "VK Jrnl SSD-5329 tst",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:19",
     "ORDER_NUMBER": 1111492,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "VK Jrnl SSD-5329 tst",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:19",
     "ORDER_NUMBER": 1111493,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 08:23",
     "ORDER_NUMBER": 1111494,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 09:28",
     "ORDER_NUMBER": 1111495,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 09:33",
     "ORDER_NUMBER": 1111496,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DM_JRNL 4 Jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 09:50",
     "ORDER_NUMBER": 1111497,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 09:52",
     "ORDER_NUMBER": 1111498,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "Portal book",
     "ORDER_STATUS": "COMPLETED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 09:57",
     "ORDER_NUMBER": 1111499,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "DM_BOOK 4 Jan1",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 10:19",
     "ORDER_NUMBER": 1111500,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DM_JRNL 4 Jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 10:24",
     "ORDER_NUMBER": 1111501,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "Portal Jrnl",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 10:24",
     "ORDER_NUMBER": 1111501,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "Portal Jrnl",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "COMPLETED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/04\/2024 13:18",
     "ORDER_NUMBER": 1111502,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "MKW-Test-DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 03:40",
     "ORDER_NUMBER": 1111504,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "VK Jrnl SSD-5403 tst",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 04:26",
     "ORDER_NUMBER": 1111505,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK book SSD-5403 tst",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 04:31",
     "ORDER_NUMBER": 1111506,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 04:56",
     "ORDER_NUMBER": 1111527,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK book forwarderadd",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:11",
     "ORDER_NUMBER": 1111541,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:13",
     "ORDER_NUMBER": 1111543,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK book Bill address",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:36",
     "ORDER_NUMBER": 1111558,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "RN2_DNP",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:47",
     "ORDER_NUMBER": 1111563,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "VK Jrnl DNP 5403",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:51",
     "ORDER_NUMBER": 1111567,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "staging portal order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:51",
     "ORDER_NUMBER": 1111567,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "staging portal order",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 05:55",
     "ORDER_NUMBER": 1111568,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "VK DNP Book 5403",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 06:02",
     "ORDER_NUMBER": 1111571,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DM_JRNL 5 Jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/05\/2024 06:02",
     "ORDER_NUMBER": 1111571,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DM_JRNL 5 Jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:08",
     "ORDER_NUMBER": 1112095,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:08",
     "ORDER_NUMBER": 1112095,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:08",
     "ORDER_NUMBER": 1112095,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:08",
     "ORDER_NUMBER": 1112095,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:08",
     "ORDER_NUMBER": 1112095,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:45",
     "ORDER_NUMBER": 1112101,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:45",
     "ORDER_NUMBER": 1112101,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:59",
     "ORDER_NUMBER": 1112104,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 11:59",
     "ORDER_NUMBER": 1112104,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 12:01",
     "ORDER_NUMBER": 1112105,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 12:38",
     "ORDER_NUMBER": 1112107,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl 10jan",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 14:03",
     "ORDER_NUMBER": 1112110,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "MKW-csv-test",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 19:40",
     "ORDER_NUMBER": 1112126,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "TEST-0110241939-UK",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/10\/2024 19:44",
     "ORDER_NUMBER": 1112127,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 01:49",
     "ORDER_NUMBER": 1112140,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": 123456,
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 02:23",
     "ORDER_NUMBER": 1112154,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DNP MAX",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 03:02",
     "ORDER_NUMBER": 1112160,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DNP MAX",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 03:09",
     "ORDER_NUMBER": 1112163,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "DNP MAX",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 06:38",
     "ORDER_NUMBER": 1112195,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl ziggy",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 07:39",
     "ORDER_NUMBER": 1112200,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl ziggy",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 07:50",
     "ORDER_NUMBER": 1112203,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "TEST-0110241951-UK",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 06:16",
     "ORDER_NUMBER": 1112193,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "MultiItems Jrnl ziggy",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 02:53",
     "ORDER_NUMBER": 1112155,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": 123456,
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 07:53",
     "ORDER_NUMBER": 1112204,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "TEST-0110241951-UK",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 07:57",
     "ORDER_NUMBER": 1112205,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 08:10",
     "ORDER_NUMBER": 1112210,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 08:28",
     "ORDER_NUMBER": 1112218,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 08:36",
     "ORDER_NUMBER": 1112227,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 09:47",
     "ORDER_NUMBER": 1112243,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQJrnls",
     "PURCHASE_ORDER_NUMBER": "Jrnl CSV 5414",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "ONHOLD",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 10:03",
     "ORDER_NUMBER": 1112249,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "Book CSV 5414",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 10:35",
     "ORDER_NUMBER": 1112251,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "MKW-csv-test2",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 10:35",
     "ORDER_NUMBER": 1112254,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "MKW-csv-test2",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 16:24",
     "ORDER_NUMBER": 1112280,
     "SGGS_PUBLISHER_ACRONYM": "MANNING",
     "PURCHASE_ORDER_NUMBER": "639702T4",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 16:44",
     "ORDER_NUMBER": 1112283,
     "SGGS_PUBLISHER_ACRONYM": "MANNING",
     "PURCHASE_ORDER_NUMBER": "639702T7",
     "ORDER_STATUS": "CANCELED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/11\/2024 17:02",
     "ORDER_NUMBER": 1112286,
     "SGGS_PUBLISHER_ACRONYM": "MANNING",
     "PURCHASE_ORDER_NUMBER": "639702T9-GERMANY",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI DE (Germany)",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/12\/2024 02:22",
     "ORDER_NUMBER": 1112299,
     "SGGS_PUBLISHER_ACRONYM": "UAT-TNQBooks",
     "PURCHASE_ORDER_NUMBER": "ziggy test",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "INPROCESS",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/12\/2024 04:18",
     "ORDER_NUMBER": 1112333,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "CSV test RN",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/12\/2024 04:19",
     "ORDER_NUMBER": 1112336,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "CSV test RN",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/12\/2024 06:12",
     "ORDER_NUMBER": 1112342,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "test RN -5427",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/12\/2024 06:12",
     "ORDER_NUMBER": 1112345,
     "SGGS_PUBLISHER_ACRONYM": "UAT-SPABooks",
     "PURCHASE_ORDER_NUMBER": "test RN -5427",
     "ORDER_STATUS": "FAILED",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI UK",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    },
    {
     "DATE_ADDED": "01\/12\/2024 17:11",
     "ORDER_NUMBER": 1112362,
     "SGGS_PUBLISHER_ACRONYM": "MANNING",
     "PURCHASE_ORDER_NUMBER": "639703T5-GERMANY",
     "ORDER_STATUS": "INPROCESS",
     "DNP_ORDER_STATUS": "FAILED",
     "DNP_PRODUCTION_PLANT_NAME": "CPI DE (Germany)",
     "Title_Handshake":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     "Order_Acknowledgement":<CancelOutlinedIcon sx={{color: red[700], width: 120, fontSize:25  }} />,
     "Order_Shipped":<TaskAltIcon color="success"  sx={{ width: 120 }} />,
     
    }
   ];

const DataTable = () => {
    //should be memoized or stable
    const columns = useMemo(
        () => [
            {
                accessorKey: 'DATE_ADDED', //access nested data with dot notation
                header: 'Date Added',
                size: 150,
            },
            {
                accessorKey: 'ORDER_NUMBER',
                header: 'Order #',
                size: 150,
            },
            {
                accessorKey: 'SGGS_PUBLISHER_ACRONYM', //normal accessorKey
                header: 'Publisher',
                size: 200,
            },
            {
                accessorKey: 'PURCHASE_ORDER_NUMBER',
                header: 'Customer PO #',
                size: 150,
            },
            {
                accessorKey: 'ORDER_STATUS',
                header: 'CSR Status',
                size: 150,
            },
            {
                accessorKey: 'DNP_ORDER_STATUS',
                header: 'DNP Order Status',
                size: 150,
            },
            {
                accessorKey: 'DNP_PRODUCTION_PLANT_NAME',
                header: 'Production Plant',
                size: 150,
            },
            {
                accessorKey: 'Title_Handshake',
                header: 'Title Handshake',
                size: 150,
            },
            {
                accessorKey: 'Order_Acknowledgement',
                header: 'Order Acknowledgement',
                size: 150,
            },
            {
                accessorKey: 'Order_Shipped',
                header: 'Order Shipped',
                size: 150,
            },
           
        ],
        [],
    );

    const table = useMaterialReactTable({
        columns,
        data, //data must be memoized or stable (useState, useMemo, defined outside of this component, etc.)
    });

    return <MaterialReactTable table={table} />;
};

export default DataTable;
